<?php
// continue.php - validate token generated by webhook and redirect to bank flow
$cfg = require __DIR__ . '/config.php';
$token = $_GET['token'] ?? null;
if (!$token) {
    http_response_code(400);
    echo 'Token requerido';
    exit;
}

$dir = __DIR__ . '/callback_sessions';
$file = $dir . '/' . basename($token) . '.json';
if (!file_exists($file)) {
    http_response_code(404);
    echo 'Token no válido o expirado';
    exit;
}

 $data = json_decode(file_get_contents($file), true);
// TTL for tokens (seconds) - can be set in bancos/config.php as 'callback_ttl'
$cfgGlobal = require __DIR__ . '/config.php';
$ttl = isset($cfgGlobal['callback_ttl']) ? (int)$cfgGlobal['callback_ttl'] : 300; // default 5 minutes

if (isset($data['created_at']) && (time() - (int)$data['created_at'] > $ttl)) {
    @unlink($file);
    http_response_code(410);
    echo 'Token expirado';
    exit;
}
if (!$data) {
    http_response_code(500);
    echo 'Error leyendo token';
    exit;
}

// create a browser session for continuity
session_start();
$_SESSION['current_transaction'] = $data['transaction_id'] ?? null;
$_SESSION['current_action'] = $data['action'] ?? null;
$_SESSION['callback_data'] = $data; // guardar todos los datos originales

// Mark token as used (keep for re-validation if needed)
$used_marker = $file . '.used';
file_put_contents($used_marker, date('Y-m-d H:i:s'));

// Redirect to index.php (the bank's entry point) - it will use the session data
header('Location: ./index.php');
exit;




